name: Azure Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login using Service Principal
        run: |
          az login --service-principal \
            -u "${{ secrets.AZURE_APP_ID }}" \
            -p "${{ secrets.AZURE_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"
          
          az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Verify Subscription
        run: az account show
