name: Azure Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure CLI Login (Managed Identity)
        run: |
          az login --identity --allow-no-subscriptions
          az account set --subscription "<YOUR_SUBSCRIPTION_ID>"

      - name: Verify Subscription
        run: az account show
   
